export const actionTypes = {
  REGISTRATION: "REGISTRATION",
  LOG_IN: "LOG_IN",
  LOG_OUT: "LOG_OUT",
  GET_CURRENT_USER: "GET_CURRENT_USER",
  UPDATE_CURRENT_USER: "UPDATE_CURRENT_USER",
  UPDATE_PASSWORD: "UPDATE_PASSWORD",
  SUBSCRIBE_USER: "SUBSCRIBE_USER",
  UNSUBSCRIBE_USER: "UNSUBSCRIBE_USER",
  CREATE_NEW_POST: "CREATE_NEW_POST",
  EDIT_POST: "EDIT_POST",
  DELETE_POST: "DELETE_POST",
};
