export const actionTypes = {
  REGISTRATION: "REGISTRATION",
  LOG_IN: "LOG_IN",
  LOG_OUT: "LOG_OUT",
  GET_CURRENT_USER: "GET_CURRENT_USER",
  UPDATE_CURRENT_USER: "UPDATE_CURRENT_USER",
  UPDATE_PASSWORD: "UPDATE_PASSWORD",
};
