export const actionTypes = {
  GET_USER_BY_ID: "GET_USER_BY_ID",
  GET_USERS_BY_LOGIN: "GET_USERS_BY_LOGIN",
  FOLLOW_UNFOLLOW_USER: "FOLLOW_UNFOLLOW_USER",
  GET_FOLLOWERS_AND_FOLLOWING_BY_USER_ID:
    "GET_FOLLOWERS_AND_FOLLOWING_BY_USER_ID",
};
