export const actionTypes = {
  GET_COMMENT_BY_POST_ID: "GET_COMMENT_BY_POST_ID",
  DELETE_COMMENT_BY_COMMENT_ID: "DELETE_COMMENT_BY_COMMENT_ID",
  CREATE_COMMENT: "CREATE_COMMENT",
  UPDATE_COMMENT_TEXT: "UPDATE_COMMENT_TEXT",
};
